Structural 2 - Half Circle to Parabolla
fs-feup/quizzes-calculators pull request #10
Opened 2024-11-28 15:51 UTC by BrunoDias201907828

2024-11-29 16:17 UTC, Flopes55 commented on structural/script.js
> +const formula_half_circle_I_x_bar = [
There is something wrong with this one 
if x bar = 1 then radius = 1.7373686553786964 
if radius =  1.7373686553786964 then x bar = 9.869604401089356

2024-11-29 16:33 UTC, Flopes55 requested changes

2024-11-29 16:33 UTC, Flopes55 commented on structural/script.js
> +const formula_half_circle_I_x_bar = [
There is something wrong with this one 
if x bar = 1 then radius = 1.7373686553786964 
if radius =  1.7373686553786964 then x bar = 9.869604401089356

2024-11-29 16:33 UTC, Flopes55 commented on structural/script.js
> +const formula_quarter_circle_I_x_bar = [
same with this one
if  I x bar = 1 then radius = 2.0660911663590564
if radius = 2.0660911663590564 then I x bar =  9.869604401089358

2024-11-29 16:33 UTC, Flopes55 commented on structural/script.js
> +const formula_quarter_circle_I_y_bar = [
same as previous one

2024-12-01 21:24 UTC, Flopes55 approved these changes
no errors found

2024-12-05 14:44 UTC, teixdavide commented
Overall good. Quarter Elipse I y bar is wrong

2024-12-05 14:44 UTC, Davide64-dev requested changes
Overall good. Quarter Elipse I y bar is wrong

2024-12-06 10:54 UTC, Davide64-dev approved these changes

2024-12-06 10:54 UTC, merged