feat: stuctural 2
fs-feup/quizzes-calculators pull request #17
Opened 2024-12-16 14:14 UTC by lourenco31

2024-12-17 17:27 UTC, Davide64-dev requested changes
Overall, everything working, just add the formulas to the sidebar

2025-01-03 23:15 UTC, marhcouto commented
- It can be a little confusing to understand how it works, maybe a short indication could be good and it would be nice if the values would fill-in in the empty box, but that's a bit of a matter of taste.
- It would be handy to have the labels also before the text boxes, so that they don't disappear when you write the text
Apart from this, it seems to function properly

2025-01-06 13:41 UTC, Davide64-dev commented
> * It can be a little confusing to understand how it works, maybe a short indication could be good and it would be nice if the values would fill-in in the empty box, but that's a bit of a matter of taste.
> * It would be handy to have the labels also before the text boxes, so that they don't disappear when you write the text
>   Apart from this, it seems to function properly

Can you explain the first topic better?

2025-01-07 09:43 UTC, marhcouto commented
Opah é dificil perceber à priori em que situações é que aquilo é utilizado, é mais isso, estava a sugerir uma breve descrição inicial

2025-01-22 13:23 UTC, merged